### ISSUE TITLE
Build linux/arm64 Image

### ISSUE THREAD

**Issue by ghost** [coryb/dfpp#1]
Hi there!
Could you maybe add a linux/arm64 arch image to your dockerhub? Executing this (even though I try to run it in the amd64 platform) throws an error that looks like it has to do something with very old amd64 images:
```
docker run --platform linux/amd64 --rm -i -v $(pwd):/root:ro coryb/dfpp $$VERSION.Dockerfile > Dockerfile
```

A arm64 image would be nice for all the apple silicon folks out there, but it may also be fine if you rebuild your latest image with the newest dependencies.

Oh here's the error btw:
```

Unable to find image 'coryb/dfpp:latest' locally
latest: Pulling from coryb/dfpp
40aae34b26d5: Pull complete 
db2213e2f7bc: Pull complete 
Digest: sha256:46120dc13aaf2799441206ca24a926ea42a547a82d4643fe7367479596c9b200
Status: Downloaded newer image for coryb/dfpp:latest
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x689293, 0x9)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc420022000, 0xc420032000)
        /usr/local/go/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0x697d08, 0x0)
        /usr/local/go/src/runtime/proc.go:1628 +0x137
runtime.main.func1()
        /usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x7b5c00)
        /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc42001e788 sp=0xc42001e780
runtime.main()
        /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc42001e7e0 sp=0xc42001e788
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42001e7e8 sp=0xc42001e7e0
```

**Comment by coryb** [comment]
I have released a multiplatform version, `coryb/dfpp:1.0.5`, hopefully it will work for you
